---
title: "Demo20160710"
author: "Luke Fan"
date: "2016年7月10日"
output: html_document
---



```{r}
library(rvest)
appleurl = 'http://www.appledaily.com.tw/realtimenews/article/entertainment/20160710/904877/伊能靜生女照被當廣告　坐月子還要忙告人'
h1 = read_html(appleurl) %>% html_nodes('#h1') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
trans = read_html(appleurl) %>% html_nodes('.trans') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
clicked = read_html(appleurl) %>% html_nodes('.clicked') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
gggstime = read_html(appleurl) %>% html_nodes('.gggs time') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
```
##建立內文元素剖析函式
```{r}
getArticle = function(appleurl, category){
  h1 = read_html(appleurl) %>% html_nodes('#h1') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
  trans = read_html(appleurl) %>% html_nodes('.trans') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
  clicked = read_html(appleurl) %>% html_nodes('.clicked') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
  gggstime = read_html(appleurl) %>% html_nodes('.gggs time') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
  
  df = data.frame(title = h1, article = trans, click = clicked, dt = gggstime, category = category)
  df
}
```





```{r}
dfall = data.frame(title = character(), 
                   article= character(),
                   click = character(), 
                   dt =character(),
                   category= character())
getURL <- function(applenews){  
  applenews = 'http://www.appledaily.com.tw/realtimenews/section/new/'
  rtddt = read_html(applenews) %>% html_nodes('.rtddt a')
  for (ele in rtddt){
    categorys = ele %>% html_nodes('h2') %>% 
      html_text() %>% iconv(from='UTF-8', to='UTF-8')
    links = ele %>% html_attr('href') %>% 
      iconv(from='UTF-8', to='UTF-8')
    links = paste0('http://www.appledaily.com.tw', links)
    df = getArticle(links, categorys)
    dfall <- rbind(dfall,df)
    
  }
  dfall
}
```


```{r}
newsall = getURL('http://www.appledaily.com.tw/realtimenews/section/new/')
View(newsall)
```

##剖析資料
```{r}
#判斷類別
class(newsall[ 1 , "article" ])
# 將factor 轉型回character
newsall$article = as.character(newsall$article)
# write in magrittr %>%
strsplit(newsall[ 1 , "article" ], 'googletag') %>% .[[1]] %>% .[1] %>% trimws() %>% strsplit(., '  +') %>% .[[1]] %>% paste(., collapse = ' ')
```


## 轉換人氣數
```{r}
#判斷型態
class(applenews$click)
```


```{r}
#將factor 轉型回character
newsall$click = as.character(newsall$click)

#抽取一欄
gsub('.{2}\\((\\d+)\\)', '\\1',x = newsall[1,'click'])
```



```{r}
#抽取所有列
gsub('.{2}\\((\\d+)\\)', '\\1',x = newsall[,'click'])
```

##排序
```{r}
applenews$click = 
as.integer(gsub('.{2}\\((\\d+)\\)', '\\1',x = applenews$click))

sort(applenews$click)
```

```{r}
head(applenews[order(applenews$click, decreasing = TRUE), c('title', 'click') ], 5)
```


##抓取分頁資訊
```{r}
#產生30頁新聞
appleurl = 'http://www.appledaily.com.tw/realtimenews/section/new/' 
for (i in 1:30){
  paste0(appleurl, i)
}

sapply(1:30, 
       function(e){ 
            paste0(appleurl, e)
         }
       )
```

